### ISSUE TITLE
Videos for Synthetic test dataset inaccessible

### ISSUE THREAD

**Issue by Rishabh-Samra** [guanyingc/DeepHDRVideo-Dataset#1]
While I was trying to access Videos (POKER FULLSHOT AND CAROUSEL FIREWORKS) from the link(https://www.hdm-stuttgart.de/vmlab/hdm-hdr-2014/), which was used to create synthetic test datasets as mentioned in the repository, I couldn't find the link of the videos. I also tried to access it by using ftp and the mentioned server name but that's not reachable. Please let me know as how I can access the videos and the other details.

**Comment by guanyingc** [comment]
Hi, the source HDR videos can be found in Google Drive (Synthetic_Dataset/HDR_Source_Videos_for_Sythetic_Testset.tgz). 
https://drive.google.com/drive/folders/1WcQIwW1OBcAq7pei0318zlALv7KCyD7m?usp=sharing
