### ISSUE TITLE
Creation of scenes.txt file

### ISSUE THREAD

**Issue by Karthik-1998** [guanyingc/DeepHDRVideo-Dataset#2]
Can you please tell, how to create scenes.txt file?

**Comment by guanyingc** [comment]
Hi, may I know which dataset?
The scenes.txt should be a list that contains the scene directory. For example, you can use "ls > scenes.txt".

**Comment by Karthik-1998** [comment]
Hi ,

Yeah got it. Are you also storing the exposures of each scene in scenes,txt
file.If yes how to do that?

**Comment by guanyingc** [comment]
Hi, you may refer to the processed TOG13 dataset for example of Exposures.txt
https://drive.google.com/drive/folders/1UCqUnSWXNZPdxEABKi-jwoYPD8dnKTBL?usp=sharing
