### ISSUE TITLE
Can you give more information about synthetic training dataset?

### ISSUE THREAD

**Issue by fonte-fs** [guanyingc/DeepHDRVideo-Dataset#3]
Dear,

Thank you for sharing the dataset.

I downloaded hallway2 of your synthetic dataset. The name of its subfolder is all like 'clip_0000XX.0000XX_X', and every folder contains 7 images. Are they all HDR images or generated LDR images? Which is the groundtruth of every sample? 

And for each subfolder, it contains one txt file which contains '99.9' for every line. What do they mean？

**Comment by guanyingc** [comment]
Hi,
1. They are all 16bit HDR images saved in .npy file. The jpg file is LDR image for visualization.
2. Currently, our training code loads HDR images and re-expose them to LDR images in an online manner.
![image](https://user-images.githubusercontent.com/8651158/144434833-9f6206cf-5b6e-4972-a1a5-10754cdd093e.png)

3. The number of '99.9' can be safely ignored. This parameter is depreciated.

**Comment by fonte-fs** [comment]
Thanks for your reply! It really helps.

I have another question here. Did you add noise to training samples like you did on synthetic testing data?

And How about FPS about original videos of synthetic dataset？

**Comment by guanyingc** [comment]
Yes, we add noise to the low-exposure frames during training. For example, in https://github.com/guanyingc/DeepHDRVideo/blob/5f87d882ce774386327ad16b092d058ab0f60b28/models/hdr2E_model.py#L128

I am not sure about the exact FPS of the used online HDR video dataset. Please check their corresponding websites for more details. Thanks.

**Comment by fonte-fs** [comment]
Thanks for your assistance and sharing your time for my issue！I will close this issue.
