### ISSUE TITLE
More details about synthetic dataset

### ISSUE THREAD

**Issue by fonte-fs** [guanyingc/DeepHDRVideo-Dataset#4]

**Comment by fonte-fs** [comment]
Dear，

Sorry to bother you again. I'm interested in HDR video reconstruction, especially your nice work published in ICCV21.  Currently I still have a couple of questions. It couldn’t be better if you can answer for me. 

1. In last issue, I mentioned that your sub-folders of your synthetic datasets are all named like  'clip_A.B_C' (eg, clip_000011.000004_0). Could you please explain what A，B and C mean？Are they mean the timestamp or something?

2. What's more，samples of your synthetic datasets contains camera motion but your real-world dynamic datasets don't contain camera motion ( only with human and object motion )，so is this a deficiency? How do you think about it?

3. You opened Google Drive for source videos of synthetic testing datasets. Do you have source videos of synthetic training datasets on Google Drive？

Sorry to bother you again.

**Comment by guanyingc** [comment]
Hi, 
1. Note that only the last component is added by me (i.e., C in the example you mentioned), which indicates the patch index. A and B exist in the original image name of the source video.

2. The real-world dynamic dataset has two parts, one is dynamic with GT and the other is dynamic without GT. The dynamic with GT dataset does not contain camera motion, which is mentioned in the paper. It is a kind of deficiency, but we can apply random global motion to simulate camera motion. The dynamic without GT contains both camera motion and object motion, but no ground-truth HDRs are provided.

3. Yes, please check the source videos of synthetic training dataset in the `Online_HDR_Dataset/` directory of the shared https://drive.google.com/drive/folders/10CzRavlDob7QkI5zAtQSWLfxeOUPRFZD?usp=sharing

**Comment by fonte-fs** [comment]
It‘s so kind of you to give clear explanation！Thanks you！

1. I still have some questions. What's the meaning of name of sub-folder in your real-world dynamic dataset? (For example, scene_000_ref_high_step1 or scene_002_ref_low_step4  is  with the  format of scene_A_ref_B_C. Maybe A is scene index and B is the exposure of reference frame. And what about C ?)

2. You also mentioned utilizing Vimeo 90-K dataset.  Are this dataset and  their source videos accessible on Google Drive？

**Comment by guanyingc** [comment]
1. For the real-world dynamic dataset, A and B are exactly the same meaning as you pointed out. C is the sampling step between neighboring, corresponding to the sentence "For each reference frame with GT HDR, we also created a pair with a larger motion by sampling the neighboring frames in a frame interval of 2, which doubles the number of pairs." in the paper.  
![image](https://user-images.githubusercontent.com/8651158/145711107-22ee3425-e2d4-472f-b15b-7ae725ea540d.png)

2. Please download Vimeo 90K dataset in http://data.csail.mit.edu/tofu/dataset/vimeo_septuplet.zip from http://toflow.csail.mit.edu/.

**Comment by fonte-fs** [comment]
Thank you very much for your reply！

I understand clearly. If I have questions later, I will create a new issue. Currently I will close this issue.

Wish you a wonderful new week！
