### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by tuvovan** [guanyingc/DeepHDRVideo-Dataset#5]
Hi,

Thank you for your hard work. I have a question regarding to the data format. 

What is the range of the HDR images? Are they between 0 and 1 or the original value?

Thanks!

**Comment by guanyingc** [comment]
Hi, 

The HDR images are computed with the LDR images, and are in [0,1]. 

But we have provided the raw LDR images with the corresponding exposures, you might be able to compute the original value.

**Comment by syujung** [comment]
Hello, thank you for your hard work. I have a question regarding to the gen_syn_train_dataset.py
,can you provide the code of self.prepare_list and the scenes.txt ? There is a bug in gen_syn_train_dataset.py,thank you for your hard work !

**Comment by guanyingc** [comment]
Hi, please refer to https://github.com/guanyingc/DeepHDRVideo-Dataset/issues/2 for creating scenes.txt. In fact it is just a file stores the directories.
