### ISSUE TITLE
About the metadata of real benchmark datasets

### ISSUE THREAD

**Issue by syujung** [guanyingc/DeepHDRVideo-Dataset#6]
Dear Guanying，
     I have a question about the ISO and Aperature of real benchmark datasets. Can you provide the  ISO and Apearture of the  scene in your datasets？ I can not find the ISO and Aperature in “camdata.npy ” .
     Looking forward to your reply ！

**Comment by guanyingc** [comment]
Hi, we didn't record the ISO and aperature. We used an industry camerea for data capturing, and adjust the "gain" to control the brightness.

**Comment by syujung** [comment]
Thank you for your reply！ Do you mean the gain of an industry camera is the same as  ISO of a consumer grade camera？

**Comment by guanyingc** [comment]
Sorry, I am not very sure. I only found the configuration of 'gain' when capturing the data.

**Comment by syujung** [comment]
Ok，I got it！ Thank you！
