### ISSUE TITLE
About the data capturing devices

### ISSUE THREAD

**Issue by syujung** [guanyingc/DeepHDRVideo-Dataset#7]
Dear guanying，
      In this repository，you mentioned you used 3 lens ，1 Basler camera and 1 usb 3.0 cable，and i also want to buy an industry camera to capture data，are there any other devices that i need to buy？
       Looking forward to your reply！

**Comment by guanyingc** [comment]
Hi, no other devices are neede. You just need a computer to control the camera.

**Comment by syujung** [comment]
I got it！
Thank you！
