### ISSUE TITLE
No permission to access Google Drive

### ISSUE THREAD

**Issue by qtlark** [guanyingc/DeepHDRVideo-Dataset#8]
I am sorry to bother you. When I try to access Google Drive today, I find that I don't have the relevant permissions to download. Can you please share the permissions, I would appreciate it if you public the access!

**Comment by guanyingc** [comment]
Sorry. My unlimited Google drive account has been deactived. Please download them from Onedrive.
https://connecthkuhk-my.sharepoint.com/:f:/g/personal/u3004356_connect_hku_hk/Ep3hSvMQo8tIhesJHwgFv64Bq1R7v6oi9hnLshzw55vedg?e=D2bBxr

**Comment by qtlark** [comment]
Thank you for sharing! But I found that the hdr-hdm dataset is not in the OD. If it's convenient, please upload it to help everyone get rid of the slow FTP transfer. Thanks！

**Comment by guanyingc** [comment]
As the hdr-hdm is too large, around 100GB, One drive cannot upload such a  huge dataset.

**Comment by qtlark** [comment]
If it's available, please upload it to Baidu Yun or other net drive. FTP causes me a lot of trouble due to poor network condition. Hope you can help me and others in the same situation. In the end, thank you for your patient answer and generous help.

**Comment by guanyingc** [comment]
Please donwload it from 链接: https://pan.baidu.com/s/1IzEZiqC9QQcVwjgoqBHccA?pwd=tzdf 提取码: tzdf

**Comment by guanyingc** [comment]
Oh, I found that One drive also has this copy

![image](https://github.com/guanyingc/DeepHDRVideo-Dataset/assets/8651158/1b0ac504-8b4a-4eb8-850b-952e5ea12ff9)

**Comment by qtlark** [comment]
Thanks again for your generous help. Best wishes to you!
