### ISSUE TITLE
OneDrive link has been removed

### ISSUE THREAD

**Issue by chachadi** [guanyingc/DeepHDRVideo-Dataset#9]
the link has been removed
![Snipaste_2024-03-22_16-18-01](https://github.com/guanyingc/DeepHDRVideo-Dataset/assets/64918922/0ebc39a0-cd8a-429f-81c3-cc24f9f19d52)

**Comment by guanyingc** [comment]
I am sorry that my OneDrive account is currently unable to host this dataset. I am in the process of uploading the dataset to BaiduYun.

**Comment by guanyingc** [comment]
The dataset can be downloaded from BaiduYun now.
